dnp = "N/A"


arizonaCardinals = {
    "Kyler Murray" : 17.9,
    "James Conner" : 15.0,
    "Trey McBride" : 12.9,
    "Marvin Harrison Jr" : 11.7,
    "Michael Wilson" : 7.7,
    "Emari Demercado" : 4.5,
    "Greg Dortch" : 4.5,
    "Trey Benson" : 4.2,
    "Elijah Higgins" : 3.8,
    "Deejay Dallas" : 0.7,
    "Tip Reiman" : 0.3,
    "Zay Jones" : 0.3,
    "Xavier Weaver" : 0.0,
    "Zach Pascal" : 0.0,
    "Travis Volovek" : 0.0,
    "Dan Chisena" : dnp,
    "Clayton Tune" : -0.6,
    "Defense" : 5.7
}
atlantaFalcons = {
    "Bijan Robinson" : 19.1,
    "Drake London" : 15.9,
    "Kirk Cousins" : 15.3,
    "Darnell Mooney" : 14.4,
    "Kyle Pitts" : 10.1,
    "Ray Ray McCloud III" : 7.8,
    "Tyler AllGeier" : 7.1,
    "KhaDarel Hodge" : 2.3,
    "Jase McCellan" : 1.7,
    "Michael Penix Jr" : 0.6,
    "Charlie Woerner" : 0.4,
    "Casey Washington" : 0.4,
    "Avery Williams" : 0.0,
    "Ross Dwelley" : 0.0,
    "Chris Blair" : 0.0,
    "Defense/ST" : 3.4,
    "Rondale Moore" : dnp
}
baltimoreRavens = {
    "Lamar Jackson" : 25.9,
    "Derrick Henry" : 21.6,
    "Zay Flowers" : 14.2,
    "Rashod Bateman" : 10.5,
    "Mark Andrews" : 9.6,
    "Diontae Johnson" : 9.5,
    "Justin Tucker" : 8.6,
    "Justice Hill" : 7.8,
    "Isaiah Likely" : 7.7,
    "Nelson Algoholor" : 4.6,
    "Charlie Kolar" : 2.7,
    "Tylan Wallace" : 2.6,
    "Patrick Ricard" : 1.3,
    "Josh Johnson" : 0.1,
    "Keaton Mitchell" : 0.0,
    "Devontez Walker" : 0.0,
    "Deonte Harty" : 0.0,
    "Rasheen Ali" : 0.0,
    "Defense/ST" : 3.7,
    "Owen Wright" : dnp
}
buffaloBills = {
    "Josh Allen" : 19.9,
    "James Cook" : 16.6,
    "Khalil Shakir" : 12.6,
    "Amari Cooper" : 9.9,
    "Keon Coleman" : 9.3,
    "Tyler Bass" : 9.1,
    "Dalton Kincaid" : 8.2,
    "Ray Davis" : 7.0,
    "Mack Hollins" : 5.4,
    "Ty Johnson" : 4.6,
    "Curtis Samuel" : 3.3,
    "Dawson Knox" : 3.0,
    "Quentin Morris" : 0.0,
    "Reggie Gilliam" : 0.0,
    "Tyrell Shavers" : 0.0,
    "Jalen Virgil" : 0.0,
    "Mitchell Trubisky" : -0.1,
    "Defense/ST" : 8.1,
    "Damien Harris" : dnp,
    "Frank Gore Jr" : dnp,
    "Shane Buechele" : dnp,
    "KJ Hamler" : dnp,
}
carolinaPanthers = {
    "Chuba Hubbard" : 16.2,
    "Andy Dalton" : 9.8,
    "Xavier Legette" : 8.4,
    "Adam Thielen" : 8.3,
    "Bryce Young" : 7.1,
    "Jalen Coker" : 7.0,
    "Eddy Pineiro" : 5.9,
    "Ja'Tavion Sanders" : 5.7,
    "Miles Sanders" : 5.1,
    "Tommy Tremble" : 2.8,
    "David Moore" : 2.5,
    "Ian Thomas" : 0.7,
    "Raheem Blackshear" : 0.0,
    "Feleipe Franks" : 0.0,
    "Deven Thompkins" : -0.1,
    "Jonathon Brooks" : dnp,
    "Defense/ST" : 0.4
}
chicagoBears = {
    "D'Andre Swift" : 14.6,
    "Caleb Williams" : 13.4,
    "DJ Moore" : 11.1,
    "Cole Kmet" : 9.0,
    "Keenan Allen" : 8.9,
    "Rome Odunze" : 8.5,
    "Cairo Santos" : 7.0,
    "Roschon Johnson" : 6.3,
    "DeAndre Carter" : 1.8,
    "Gerald Everett" : 1.1,
    "Travis Homer" : 0.3,
    "Marcedes Lewis" : 0.1,
    "Tyler Scott" : 0.0,
    "Collin Johnson" : 0.0,
    "Tyson Bagent" : -0.4,
    "Nsimba Webster" : dnp,
    "Stephen Carlson" : dnp,
    "Defense/ST": 8.3
}
cincinattiBengals = {
    "Jamarr Chase" : 22.5,
    "Joe Burrow" : 21.1,
    "Tee Higgins" : 16.2,
    "Chase Brown" : 13.9,
    "Zack Moss" : 10.2,
    "Mike Gesicki" : 8.2,
    "Evan McPherson" : 7.3,
    "Andrei Iosivas" : 6.4,
    "Erick All JR" : 4.0,
    "Tanner Hudson" : 3.6,
    "Kendric Pryor" : 1.9,
    "Drew Sample" : 1.8,
    "Jermaine Burton" : 1.6,
    "Khalil Herbert" : 1.4,
    "Isaiah Williams" : 1.3,
    "Cam Grandy" : 1.0,
    "Trenton Irvin" : 0.8,
    "Charlie Jones" : 0.7,
    "Kendall Milton" : 0.0,
    "Jake Browning" : -0.1,
    "Chris Evans" : dnp,
    "Trayveon Williams" : dnp,
    "Tanner McLachlan" : dnp,
    "Defense/ST" : 3.4
}
clevelandBrowns = {
    "David Njoku" : 11.3,
    "Deshaun Watson" : 11.0,
    "Jerry Jeudy" : 9.2,
    "Jerome Ford" : 9.0,
    "Cedric Tillman" : 7.8,
    "Dustin Hopkins" : 6.7,
    "Nick Chubb" : 6.6,
    "Elijah Moore" : 6.4,
    "Jameis Winston" : 6.2,
    "Jordan Akins" : 4.7,
    "Dorian Thompson-Robinson" : 3.7,
    "D'Onta Foreman" : 3.1,
    "Pierre Strong Jr" : 3.0,
    "Jaelon Dardon" : 0.3,
    "Geoff Swaim" : 0.2,
    "Jamari Thrash" : 0.0,
    "Nyheim Hines" : dnp,
    "Bailey Zappe" : dnp,
    "Defense/ST" : 6.1
}
dallasCowboys = {
    "Ceedee Lamb" : 17.4,
    "Dak Prescott" : 14.6,
    "Rico Dowdle" : 12.0,
    "Brandon Aubrey" : 11.6,
    "Jalen Tolbert" : 9.7,
    "Jake Ferguson" : 9.5,
    "Brandin Cooks" : 6.1,
    "KaVontae Turpin" : 5.2,
    "Ezekiel Elliot" : 4.8,
    "Jonathan Mingon" : 2.5,
    "Hunter Luepke" : 2.3,
    "Jalen Brooks" : 2.1,
    "Dalvin Cook" : 2.0,
    "Cooper Rush" : 1.8,
    "Luke Schoonmaker": 1.5,
    "Deuce Vaughn" : 1.1,
    "Trey Lance" : 0.5,
    "Ryan Flournoy" : 0.5,
    "Brevyn Spann-Ford" : 0.4,
    "Princeton Fant" : 0.0,
    "Jalen Moreno-Cropper" : 0.0,
    "John Stephens JR" : dnp,
    "Defense/ST" : 2.8
}
denverBroncos = {
    "Bo Nix" : 16.7,
    "Courtland Sutton" : 12.0,
    "Javonte Williams" : 10.0,
    "Devaughn Vele" : 8.3,
    "Wil Lutz" : 8.1,
    "Josh Reynolds" : 7.3,
    "Jaleel Mclaughlin" : 5.9,
    "Lil'Jordan Humphrey" : 4.2,
    "Troy Franklin" : 4.0,
    "Lucas Krull" : 3.3,
    "Tyler Badie" : 3.1,
    "Adam Trautman" : 3.0,
    "Marvin Mims Jr" : 2.1,
    "Audric Estime" : 2.1,
    "Greg Dulcich" : 2.0,
    "Nate Adkins" : 1.3,
    "Jarrett Stidham" : -0.2,
    "Zach Wilson" : dnp,
    "Defense/ST" : 9.4
}
detroitLions = {
    "Jahmyr Gibbs" : 18.1,
    "Amon-Ra St.Brown" : 17.0,
    "Jared Goff" : 15.4,
    "David Montgomery" : 15.4,
    "Jameson Williams" : 11.8,
    "Jake Bates" : 9.2,
    "Sam LaPorta" : 8.8,
    "Kalif Raymond" : 5.5,
    "Tim Patrick" : 3.7,
    "Brock Wright" : 2.3,
    "Hendon Hooker" : 0.5,
    "Sione Vaki" : 0.4,
    "Craig Reynolds" : 0.3,
    "Allen Robinson" : 0.2,
    "Tom Kennedy" : 0.0,
    "Shane Zylstra" : 0.0,
    "Michael Badgley" : dnp,
    "Teddy Bridgewater" : dnp,
    "Justin Jackson" : dnp,
    "Antoine Green" : dnp,
    "Defense/ST" : 8.2,
}
greenbayPackers = {
    "Jordan Love" : 17.1,
    "Jayden Reed" : 14.8,
    "Josh Jacobs" : 14.4,
    "Malik Willis" : 11.7,
    "Tucker Kraft" : 10.7,
    "Romeo Doubs" : 10.4,
    "Brandon McManus" : 8.0,
    "Dontayvion Wicks" : 6.6,
    "Christian Watson" : 6.6,
    "Emanuel Wilson" : 5.7,
    "MarShawn Lloyd" : 2.8,
    "Luke Musgrave" : 1.8,
    "Chris Brooks" : 1.7,
    "Bo Melton" : 1.7,
    "Malik Heath" : 0.9,
    "Ben Sims" : 0.8,
    "John FitzPatrick" : 0.0,
    "AJ Dillon" : dnp,
    "Sean Clifford" : dnp,
    "Ellis Merriweather" : dnp,
    "Tyler Davis" : dnp,
    "Defense/ST" : 8.6
}
houstonTexans = {
    "Nico Collins" : 21.3,
    "Joe Mixon" : 20.8,
    "Stefon Diggs" : 15.2,
    "CJ Stroud" : 14.0,
    "Ka'Imi Fairbairn" : 11.2,
    "Tank Dell" : 9.9,
    "Dalton Schultz" : 6.0,
}

print(carolinaPanthers["Jonathon Brooks"])

